### PR TITLE
src: cpu: aarch64: eltwise: optimize jit-ed code for SVE512

### PR DESCRIPTION
**Pull request by kawakami-k**
# Description

This PR improves the JIT-ed code of eltwise for AArch64 SVE 512.

# Checklist

## General

- [x] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [x] Have you formatted the code using clang-format?

### CODE REVIEW

**Review by dzarukin — APPROVED** [review]
LGTM, thanks.

I wonder whether these versions of algorithms have less precision or it's a hardware AArch64 features? If these have lower precision, how does benchdnn testing look like?

**Comment by dzarukin** [comment]
Thank you for the contribution.

**Comment by kawakami-k** [comment]
Hi, @dzarukin 

> I wonder whether these versions of algorithms have less precision or it's a hardware AArch64 features? If these have lower precision, how does benchdnn testing look like?
The SVE instruction set has the special instruction `fexpa` as floating-point exponential accelerator.
https://developer.arm.com/documentation/ddi0596/2020-12/SVE-Instructions/FEXPA--Floating-point-exponential-accelerator-

It achieves the precision required for benchdnn test.

Thanks.

**Comment by dzarukin** [comment]
> Hi, @dzarukin
> 
> > I wonder whether these versions of algorithms have less precision or it's a hardware AArch64 features? If these have lower precision, how does benchdnn testing look like?
> 
> The SVE instruction set has the special instruction `fexpa` as floating-point exponential accelerator.
> https://developer.arm.com/documentation/ddi0596/2020-12/SVE-Instructions/FEXPA--Floating-point-exponential-accelerator-
> 
> It achieves the precision required for benchdnn test.
> 
> Thanks.

Hi @kawakami-k , I see, thank you for clarifications.

**Pull request merged**
