### PR TITLE
cpu: aarch64: fix jit_brgemm warnings

### PR DESCRIPTION
**Pull request by taoye9**
# Description

this change is to fix aarch64 compile warning so that we can enable Werror for aarch64 in the ci.

So far, we've fix t warnings inside oneDNN/src/cpu/aarch64/ folder and the following out-of-bound warning

```
In file included from /Users/runner/work/oneDNN/oneDNN/oneDNN/src/common/memory_desc_wrapper.hpp:27,
                 from /Users/runner/work/oneDNN/oneDNN/oneDNN/src/common/memory.hpp:26,
                 from /Users/runner/work/oneDNN/oneDNN/oneDNN/src/common/engine.hpp:26,
                 from /Users/runner/work/oneDNN/oneDNN/oneDNN/src/cpu/cpu_engine.hpp:26,
                 from /Users/runner/work/oneDNN/oneDNN/oneDNN/src/cpu/cpu_deconvolution_list.cpp:19:
In function 'void dnnl::impl::copy_c_op_desc(op_desc_t*, const op_desc_t*)',
    inlined from 'dnnl::impl::primitive_desc_iterator_t::primitive_desc_iterator_t(dnnl::impl::engine_t*, const dnnl::impl::op_desc_t*, const dnnl::impl::primitive_attr_t*, const dnnl::impl::primitive_desc_t*, int)' at /Users/runner/work/oneDNN/oneDNN/oneDNN/src/common/primitive_desc_iterator.hpp:50:23,
    inlined from 'dnnl::impl::status_t dnnl::impl::cpu::ref_deconvolution_bwd_data_t::pd_t::init_convolution(dnnl::impl::engine_t*)' at /Users/runner/work/oneDNN/oneDNN/oneDNN/src/cpu/ref_deconvolution.hpp:338:[66](https://github.com/oneapi-src/oneDNN/actions/runs/11017022556/job/30593938494?pr=2118#step:9:67):
/Users/runner/work/oneDNN/oneDNN/oneDNN/src/common/type_helpers.hpp:1225:23: warning: array subscript 'const dnnl::impl::op_desc_t[0]' is partly outside array bounds of 'dnnl::impl::convolution_desc_t [1]' [-Warray-bounds=]
 1225 |     switch ((int)src->kind) {
      |                  ~~~~~^~~~
In file included from /Users/runner/work/oneDNN/oneDNN/oneDNN/src/cpu/cpu_deconvolution_list.cpp:21:
/Users/runner/work/oneDNN/oneDNN/oneDNN/src/cpu/ref_deconvolution.hpp: In member function 'dnnl::impl::status_t dnnl::impl::cpu::ref_deconvolution_bwd_data_t::pd_t::init_convolution(dnnl::impl::engine_t*)':
/Users/runner/work/oneDNN/oneDNN/oneDNN/src/cpu/ref_deconvolution.hpp:331:32: note: object 'cd' of size 5720
  331 |             convolution_desc_t cd;
      |                                ^~
In function 'void dnnl::impl::copy_c_op_desc(op_desc_t*, const op_desc_t*)',
    inlined from 'dnnl::impl::primitive_desc_iterator_t::primitive_desc_iterator_t(dnnl::impl::engine_t*, const dnnl::impl::op_desc_t*, const dnnl::impl::primitive_attr_t*, const dnnl::impl::primitive_desc_t*, int)' at /Users/runner/work/oneDNN/oneDNN/oneDNN/src/common/primitive_desc_iterator.hpp:50:23,
    inlined from 'dnnl::impl::status_t dnnl::impl::cpu::ref_deconvolution_bwd_data_t::pd_t::init_convolution(dnnl::impl::engine_t*)' at /Users/runner/work/oneDNN/oneDNN/oneDNN/src/cpu/ref_deconvolution.hpp:338:66:
/Users/runner/work/oneDNN/oneDNN/oneDNN/src/common/type_helpers.hpp:1223:44: warning: array subscript 'const dnnl::impl::op_desc_t[0]' is partly outside array bounds of 'dnnl::impl::convolution_desc_t [1]' [-Warray-bounds=]
 1223 |     case primitive_kind::pkind: dst->pkind = src->pkind; break;
      |                                            ^
/Users/runner/work/oneDNN/oneDNN/oneDNN/src/common/type_helpers.hpp:1242:9: note: in expansion of macro 'CASE_OP_DESC'
 1242 |         CASE_OP_DESC(sdpa);
      |         ^~~~~~~~~~~~
/Users/runner/work/oneDNN/oneDNN/oneDNN/src/cpu/ref_deconvolution.hpp: In member function 'dnnl::impl::status_t dnnl::impl::cpu::ref_deconvolution_bwd_data_t::pd_t::init_convolution(dnnl::impl::engine_t*)':
/Users/runner/work/oneDNN/oneDNN/oneDNN/src/cpu/ref_deconvolution.hpp:331:32: note: object 'cd' of size 5720
  331 |             convolution_desc_t cd;
```
# Checklist

## General

- [x] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [x] Have you formatted the code using clang-format?

### CODE REVIEW

**Comment by theComputeKid** [comment]
Thanks for this, which compiler is that warning from? Does this mean we can turn on werror for one of the compilers now?

**Comment by taoye9** [comment]
> ci: macOS (gcc-14, g++-14, Release, 0)]

**Comment by theComputeKid** [comment]
@vpirogov and @mgouicem , can you please help with the last remaining warning, we do not know what to do with it, as it originates outside of the aarch64 codebase. This is the last issue stopping us from enabling Werror. You can see it in the ci for gcc, release.

**Comment by dzarukin** [comment]
> @vpirogov and @mgouicem , can you please help with the last remaining warning, we do not know what to do with it, as it originates outside of the aarch64 codebase. This is the last issue stopping us from enabling Werror. You can see it in the ci for gcc, release.

If you are referring to out-of-bound access to `kind`, this is worked around by `#include "common/compiler_workarounds.hpp"` in correspondent .cpp file. It's important it's .cpp, not .hpp.
If there's something else I'm missing, please let me know. Thanks.

**Comment by theComputeKid** [comment]
@taoye9 can you please try @dzarukin's suggestion. If this works, please include it in this patch. If not, we can submit what we have, and take a look later.

If the suggestion works, then if it is okay with other reviewers, please add an additional seperate commit to this PR to immediately enable Werror in our ci, and let's never worry about warnings again.

**Comment by taoye9** [comment]
> > @vpirogov and @mgouicem , can you please help with the last remaining warning, we do not know what to do with it, as it originates outside of the aarch64 codebase. This is the last issue stopping us from enabling Werror. You can see it in the ci for gcc, release.
> 
> If you are referring to out-of-bound access to `kind`, this is worked around by `#include "common/compiler_workarounds.hpp"` in correspondent .cpp file. It's important it's .cpp, not .hpp. If there's something else I'm missing, please let me know. Thanks.

@theComputeKid following @dzarukin suggestion, i add a "#include "common/compiler_workarounds.hpp" in src/cpu/cpu_deconvolution_list.cpp and the warning is gone.

**Comment by theComputeKid** [comment]
Great news! Can you please add another commit to this PR (keep them separate) and enable werror for macos ci?

**Review by mgouicem — APPROVED** [review]
Thanks for the fixes.
Could you please reword your first commit message according to guideline. Something like `aarch64: fix jit_brgemm warnings` should do.

**Comment by taoye9** [comment]
> Thanks for the fixes. Could you please reword your first commit message according to guideline. Something like `aarch64: fix jit_brgemm warnings` should do.

done.

**Pull request merged**
