### PR TITLE
doc: update Arm Compute Library description.

### PR DESCRIPTION
**Pull request by nSircombe**
# Description

This PR covers minor changes to the description of Arm Compute Library in the
documentation.
Specifically  a deprecation notice has been issued for the the Computer Vision
functions in Compute Library, and they will be removed in future, see:
https://github.com/ARM-software/ComputeLibrary

Hence this PR changes the description of Compute Library from:

> Arm Compute Library is an open-source library for computer vision and
> machine learning applications

to:

> Arm Compute Library is an open-source library for machine learning
> applications

# Checklist

## Code-change submissions

- [N/A] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally?
- [N/A] Have you formatted the code using clang-format?

### New features

- [N/A] Have you added relevant tests?
- [N/A] Have you provided motivation for adding a new feature?

### Bug fixes

- [N/A] Have you added relevant regression tests?
- [N/A] Have you included information on how to reproduce the issue (either in a github issue or in this PR)?

### CODE REVIEW

**Review by igorsafo — APPROVED** [review]
Hi @nSircombe . The changes LGTM, thanks!

Are there any API changes which might brake oneDNN build or it is computer vision part only?

**Comment by nSircombe** [comment]
Hi @igorsafo,

> Are there any API changes which might brake oneDNN build or it is computer vision part only?

Nope, no problems there - it's just the planned removal of some CV functionality, so no impact on anything we're using here -- just making sure that the details given about ACL in oneDNN are up-to-date.

**Comment by igorsafo** [comment]
@nSircombe  Got it, thanks for the explanation!

**Comment by dzarukin** [comment]
Thanks for your contribution!

**Pull request merged**
