### PR TITLE
 Fix CI failing tests for matmul and convolution

### PR DESCRIPTION
**Pull request by renato-arantes**
# Description

Tests `test_benchdnn_modeC_conv_ci_cpu` and `test_benchdnn_modeC_matmul_ci_cpu` are failing, and this patch fixes them.

## General

- [x] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [x] Have you formatted the code using clang-format?

### CODE REVIEW

**Review by theComputeKid — CHANGES_REQUESTED** [review]
There is no `upstream` CI, only CI.

**Comment by vpirogov** [comment]
Tests with GCC on c6 instances are still failing.

**Comment by theComputeKid** [comment]
Can you also change the title of the commits, thanks! Perhaps squash the second commit into the first one.

**Comment by renato-arantes** [comment]
We must close this PR because we had to revert PR #2198.

**Pull request closed without merging**
