### PR TITLE
gtests: graph: update graph gtests naming

### PR DESCRIPTION
**Pull request by ElaineBao**
# Description

Update graph gtests naming , remove inappropriate `_usm` suffix.

# Checklist

## General

- [x] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [x] Have you formatted the code using clang-format?

### CODE REVIEW

**Review by TaoLv — APPROVED** [review]

**Comment by ElaineBao** [comment]
Hi, @theComputeKid could you please take a look at this PR, the updated graph ut names will affect aarch64 CI. Thanks!

**Review by theComputeKid — APPROVED** [review]
Thanks for doing the rename!

**Comment by ElaineBao** [comment]
make test Lightweight_scans

**Comment by ElaineBao** [comment]
make test Lightweight_scans

**Comment by ElaineBao** [comment]
hi, @vpirogov this pr passes ci tests, could you please merge it at your convenience?

**Comment by vpirogov** [comment]
make test

**Comment by vpirogov** [comment]
make test

**Pull request merged**
