### PR TITLE
RFC Introducing ACL verbose

### PR DESCRIPTION
**Pull request by cfRod**
# Description

RFC to add verbose functionality in oneDNN built with ACL. 
Link to rendered document: https://github.com/cfRod/oneDNN/tree/rfc_acl_benchmark_scheduler/rfcs/20230309-Introducing-ACL-verbose

## [RFC](https://github.com/oneapi-src/oneDNN/tree/rfcs) PR

- [x] Does RFC document follow the [template](https://github.com/oneapi-src/oneDNN/blob/rfcs/rfcs/template.md#onednn-design-document-rfc)?
- [x ] Have you added a link to the rendered document?

### CODE REVIEW

**Comment by cfRod** [comment]
Adding ACL team @doviethoa-at-work

**Comment by mgouicem** [comment]
Hi @cfRod that looks fine to me. 

Note that we have recently changed the internal interface to print verbose information and make it more organized/cleaner internally. The expectation is the from now on, developers need to use [these macros](https://github.com/oneapi-src/oneDNN/blob/01e82721b0420b76f4d11361fc5e5320ac720be0/src/common/verbose.hpp#L70-L119) to print verbose information, as this allows a common mechanism across components and unified formatting.

A few notes on the proposal:
- is this information for oneDNN users or for oneDNN developers ? If the latter, maybe these prints could be enabled under debug_info.
- From the current prints, there seem to be no way to know which primitive ran which kernel. Take the example of Tensorflow where multiple primitives can run concurrently. The kernel timings would be mangled and it would not be possible to know which kernel timing maps to which primitive. Is that ok for you? To accommodate for that, we were thinking thinking to add primitive hash to profiling verbose prints. Let me know if this is something of interest to you.

**Comment by cfRod** [comment]
@mgouicem 
Thanks, I will update the implementation to use these macros. 

- It was meant for oneDNN users to see finer-grained information from ACL, hence we prefer it to be enabled for VERBOSE settings >=2 and release mode.
- acl_set_threading() is high-level function that sets up the threading to be used by ACL. 
For default scheduler used by ACL, it sets the number of threads. We used this function "acl_thread_bind()" previously to do this, I have just moved it inside "set_acl_threading()" now. Previously, we also set up the ThreadpoolScheduler using acl_set_custom_scheduler() which also has been moved inside "acl_set_threading". See previous version https://github.com/oneapi-src/oneDNN/blob/f813d379eab60749a2f1f46a30a6f4eedae89046/src/cpu/cpu_engine.hpp#L167
I have just moved all of these to one place. 
```
void set_acl_threading() {
#if DNNL_CPU_THREADING_RUNTIME == DNNL_RUNTIME_OMP
    acl_thread_bind();
    if (get_verbose() >= 2) { acl_set_benchmark_scheduler_default(); }
#endif
#if DNNL_CPU_THREADING_RUNTIME == DNNL_RUNTIME_THREADPOOL
    if (get_verbose() >= 2) {
        acl_set_benchmark_scheduler_tp();
    } else {
        acl_set_threadpool_scheduler();
    }

#endif
```
Regarding your point about user creating two engines concurrently, could you elaborate when such a case might occur? I have not seen it in the framework integration.
>Also is there a risk that users call this function outside of oneDNN, and that oneDNN overrides their setting?
I believe this was happening previously as well but again is there a use-case in the ML framework side for this?

>From the current prints, there seem to be no way to know which primitive ran which kernel. 
That would be handy to have the hash  such that we could tie the values to ACL kernel called for that primitive.

**Comment by cfRod** [comment]
>In Tensorflow, engines are created every time an op is run. Here is an example for [pooling](https://github.com/tensorflow/tensorflow/blob/a9dc87b3769835fb7a688bf5cb2b94431fb78697/tensorflow/core/kernels/mkl/mkl_avgpooling_op.cc#L178) and [conv](https://github.com/tensorflow/tensorflow/blob/a9dc87b3769835fb7a688bf5cb2b94431fb78697/tensorflow/compiler/xla/service/cpu/runtime_conv2d_mkl.cc#L63). If two ops are run concurrently ([inter-op parallelism](https://www.tensorflow.org/api_docs/python/tf/config/threading)), then there will be two engines created concurrently in two separate threads.

Got it, in this case it should set up ACL threading once, since we use std::call_once for all the functions ... See, https://github.com/oneapi-src/oneDNN/blob/f813d379eab60749a2f1f46a30a6f4eedae89046/src/cpu/aarch64/acl_thread.cpp#L29

>This was a hypothetical scenario. This could typically happen if an application links to dnnl and to another library using acl as well.

If we start two separate instance of oneDNN, then they each have two separate instances of ACL. Each instance of ACL can only have a single pointer to a scheduler. This refactoring does not change existing behaviour.

>We have that in our backlog. I will update you as soon as we get that ready.

Thanks!

**Comment by cfRod** [comment]
Hi @mgouicem , I have made the changes based on the new verbose macros.

**Comment by cfRod** [comment]
I will raise a PR from the branch once the RFC is accepted. Thanks!

**Review by igorsafo — APPROVED** [review]

**Pull request merged**
