### PR TITLE
github: workflows: update skip test on aarch64 ci

### PR DESCRIPTION
**Pull request by taoye9**
# Description

remove aarch64 ci solved testcases from skip list.

wait for PR: https://github.com/oneapi-src/oneDNN/pull/2215 to be merged.

# Checklist

## General

- [x] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [x] Have you formatted the code using clang-format?

### CODE REVIEW

**Comment by theComputeKid** [comment]
@mgouicem : Are the PR checks going crazy again?

```
Message length: OK
Message scope:  FAILED: Commit message does not include scope
fa1ede9ec82a0cb7627bcc2cf03e6a6ce0028e06 github: workflows: update skip test on aarch64 ci
```

**Comment by theComputeKid** [comment]
@taoye9 can you rebase and force push again for a clean history without merge commits? Thanks.

**Comment by taoye9** [comment]
> @mgouicem : Are the PR checks going crazy again?
> 
> ```
> Message length: OK
> Message scope:  FAILED: Commit message does not include scope
> fa1ede9ec82a0cb7627bcc2cf03e6a6ce0028e06 github: workflows: update skip test on aarch64 ci
> ```

the new commit message is of wrong format.

**Review by Sqvid — APPROVED** [review]
LGTM

**Comment by theComputeKid** [comment]
@mgouicem can we merge this so we can increase our test coverage? Thanks.

**Pull request merged**
