### PR TITLE
cpu: aarch64: acl: fix inner_prod test failure and improve validation

### PR DESCRIPTION
**Pull request by diaena**
# Description

This PR improves testing and validation for ACL primitives.
In particular, it addresses a failing test identified in `test_ip_all`:
```
./benchdnn --ip --stag=ba --wtag=ba --dtag=ab mb16ic16oc16
```
This testcase is unsupported and the fix is adding a guard against it.

The PR also adds test_ip_acl, a  benchdnn test harness that is specific to Arm Compute Library.

We also made small improvements to the validation of the Arm Compute Library primitives.

Changes:
* Fix test failure by guarding against src/dst layout mismatch
* Add ACL_CHECK_SUPPORT and ACL_CHECK_VALID macros
* Add test_ip_acl benchdnn harness
* Remove inner_prod_utils header and impl files
* Rename acl_common_utils to shorter and better acl_utils
* Clean-up unneeded headers and namespace calls

# Checklist

## General

- [X] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [X] Have you formatted the code using clang-format?

## Performance improvements

- N/A

### New features

- N/A

### Bug fixes

- [X] Have you included information on how to reproduce the issue (either in a github issue or in this PR)?
- [X] Have you added relevant regression tests?

### CODE REVIEW

**Review by igorsafo — APPROVED** [review]

**Comment by nSircombe** [comment]
Hi @igorsafo,
Since this has now been resolved via https://github.com/oneapi-src/oneDNN/pull/1340, how should we handle this PR?

**Comment by igorsafo** [comment]
Hi @nSircombe ,
If all required changes landed as part of #1340 we can close this PR. If there are some changes left, then we need to rebase them and procced with PR promotion.

**Comment by nSircombe** [comment]
Hi @igorsafo,

With #1340 merged, that's everything from this PR done - so this can be closed.

**Comment by igorsafo** [comment]
Closing since the changes were promoted as part of #1340

**Pull request closed without merging**
