### PR TITLE
src: cpu: aarch64: Fix deconv shape

### PR DESCRIPTION
**Pull request by davsva01**
Fix an issue in deconv where ACL reduces the dimensions in TensorShape if the last dimension is of size 1.
Also add unit test to catch this issue.
Issue can be reproduced by running:
`./build/tests/benchdnn/benchdnn --deconv --dt=f32:f32:f32 mb9_ic1oc1_ih1oh1kh1sh1dh0ph0_iw55ow55kw3sw1dw0pw1`

# Checklist

## General

- [x] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [x] Have you formatted the code using clang-format?

### Bug fixes

- [x] Have you included information on how to reproduce the issue (either in a github issue or in this PR)?
- [x] Have you added relevant regression tests?

### CODE REVIEW

**Comment by snadampal** [comment]
This fixes https://github.com/pytorch/pytorch/issues/125548

**Review by dzarukin — APPROVED** [review]

**Comment by vpirogov** [comment]
This PR missed oneDNN v3.5 code freeze . I backported changes to rls-v3.5 branch (7c076b7ba767b163165981c562554e71514895e3).

**Comment by jondea** [comment]
Ah okay, thanks for that.

When was the rls-v3.5 branch made? I only saw it upstream a week or so ago, so I assumed this had made it in already. This means that #1885 hasn't gone into rls-v3.5 even though it has the v3.5 milestone and was merged. Can I make a backport PR for #1885? I know this isn't something we would usually backport, but we are relying on this in ideep/PyTorch

**Comment by vpirogov** [comment]
@jondea, release branches are created from `main` at code freeze. You can find specific dates in [Github's milestones](https://github.com/oneapi-src/oneDNN/milestones). Please go ahead and backport both PRs. The second one will be an exception, so please plan ahead next time.

**Pull request merged**
