### PR TITLE
cpu: aarch64: Expand ARM SVE support in jit_uni_pool_kernel

### PR DESCRIPTION
**Pull request by vishwascm**
# Description
Enhancement: Expand ARM SVE support in jit_uni_pool_kernel

This commit enhances the existing ARM SVE support in jit_uni_pooling to include additional vector length compatibility. The changes made are for implementation of different ARM SVE vector length.

Major Code changes:
• Updated the block size definition to accommodate other SVE vector length.
• Added 'OR' condition to extend support for other SVE vector while assigning value of 'ncsp_fmt_tag'.
• Predicate registers are set according to isa vector length.
• ldr is replaced by ld1w instruction for average pooling

# Checklist
## General

- [✓] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit? Yes
Test output is same with and without this commit.

1. make test 
```
98% tests passed, 4 tests failed out of 162

Total Test time (real) =  98.14 sec

The following tests FAILED:
         84 - test_shuffle (Subprocess aborted)
        145 - test_graph_unit_dnnl_conv_usm_cpu (Failed)
        150 - test_graph_unit_dnnl_large_partition_usm_cpu (Failed)
        158 - test_graph_unit_dnnl_sdp_decomp_usm_cpu (Subprocess aborted)
Errors while running CTest
Output from these tests are in: /home/vishwas/oneDNN/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
make: *** [Makefile:71: test] Error 8

```

2. make test_benchdnn_modeC_pool_ci_cpu/fast 

```
tests:3840 passed:2700 skipped:1140 mistrusted:0 unimplemented:0 invalid_arguments:0 failed:0 listed:0
total: 8.71s; fill: 2.78s (32%); compute_ref: 1.65s (19%); compare: 1.96s (22%);
```

3. make test_benchdnn_*
```make: *** No rule to make target 'test_benchdnn_*'.  Stop.```

### gtests

4 ./test_pooling_forward
```
[----------] Global test environment tear-down
[==========] 296 tests from 52 test suites ran. (4546 ms total)
[  PASSED  ] 296 tests.
```

5 ./test_pooling_backward
```
[----------] Global test environment tear-down
[==========] 155 tests from 24 test suites ran. (2493 ms total)
[  PASSED  ] 155 tests.
```

- [✓] Have you formatted the code using clang-format? Yes

### CODE REVIEW

**Review by igorsafo — APPROVED** [review]
Hi @vishwascm , thanks for the PR! I am a bit surprised that amount of changes on the jit side is so small to support a different vector length. Did you test it on both platforms (sve512 and sve256)?
Other than that the changes LGTM.

**Comment by vishwascm** [comment]
> Hi @vishwascm , thanks for the PR! I am a bit surprised that amount of changes on the jit side is so small to support a different vector length. Did you test it on both platforms (sve512 and sve256)? Other than that the changes LGTM.

Thank you @igorsafo  for reviewing the PR! Yes, I thoroughly tested the changes on both SVE-512 and SVE-256 vector length machines, and I'm pleased to report that everything worked smoothly on both platforms.

**Comment by abhijain1204fujitsu** [comment]
Thanks @igorsafo for your quick response and supporting for approval.

**Comment by davsva01** [comment]
Hi @igorsafo, could you please hold off merging this until we have done some benchmarking with this patch on our end? Thanks!

**Comment by igorsafo** [comment]
> Hi @igorsafo, could you please hold off merging this until we have done some benchmarking with this patch on our end? Thanks!

Hi @davsva01 , sure, it would be great to make sure there are no degradations on Arm side. Do you plan to benchmark other PRs with the similar changes?
- https://github.com/oneapi-src/oneDNN/pull/1838 
- https://github.com/oneapi-src/oneDNN/pull/1818

**Review by densamoilov — CHANGES_REQUESTED** [review]
Merging is postponed per the author's request.

**Comment by abhijain1204fujitsu** [comment]
@davsva01 , Hello David could you please share your feedback so that we can proceed for merger.

**Comment by davsva01** [comment]
> > Hi @igorsafo, could you please hold off merging this until we have done some benchmarking with this patch on our end? Thanks!
> 
> Hi @davsva01 , sure, it would be great to make sure there are no degradations on Arm side. Do you plan to benchmark other PRs with the similar changes?
> 
> * [cpu: aarch64: Expand ARM SVE support for forward convolution. #1838](https://github.com/oneapi-src/oneDNN/pull/1838)
> * [cpu: aarch64: Expand ARM SVE support for matrix multiplication #1818](https://github.com/oneapi-src/oneDNN/pull/1818)

Hi, this PR has now been tested for any regressions and all looks good! Happy to get this merged in.
Regarding the two linked PR's I have checked them out and believe they can be merged in as well, they shouldn't impact Aarch64 performance since they're not put ahead of ACL SVE 256 primitives.
Thanks!

**Comment by abhijain1204fujitsu** [comment]
@davsva01, thank you for your positive feedback.
@densamoilov, @igorsafo Kindly support to merge the PR

**Review by densamoilov — APPROVED** [review]

**Comment by igorsafo** [comment]
The changes landed into main. @vishwascm  @abhijain1204fujitsu thank you for your contribution!

**Pull request merged**
