### PR TITLE
cpu: aarch64: improve memory management safety for aarch64 kernels

### PR DESCRIPTION
**Pull request by Permanence-AI-Coder**
# Description

The code changes in this PR were generated automatically by the Permanence AI Coder and reviewed by @fwph & @jweese. This PR updates memory allocation across several objects in the aarch64 implementation. Note that the bot is configured to add the `DNNL_DISALLOW_COPY_AND_ASSIGN` where it is missing; while this is redundant with the use of unique_ptr, it provides more consistency with existing code.

on-behalf-of: @permanence-ai <github-ai@permanence.ai>

## General

- [X] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?*
- [X] Have you formatted the code using clang-format?

* note that on our build system (AWS graviton instance) the test `172 - test_benchdnn_modeC_brgemm_ci_cpu (Subprocess aborted)` is failing both on this branch AND on the main branch.

### CODE REVIEW

**Review by theComputeKid — APPROVED** [review]

**Review by theComputeKid — CHANGES_REQUESTED** [review]
I see some JIT failures that I did not expect to see (considering the contents of this change) - will look into this more.

**Review by theComputeKid — APPROVED** [review]
Issue was unrelated. LGTM. Approved.

**Comment by theComputeKid** [comment]
@vpirogov I don't know what is wrong with the bot, I approved the changes but it still shows as `At least 2 approving reviews are required`.

**Comment by vpirogov** [comment]
@theComputeKid, nothing is wrong with the bot. The repo is configured to require 2 approvals for any PR per OpenSSF recommendation.

**Pull request merged**
