### PR TITLE
cpu: aarch64: build: update Compute Library required version to 22.08

### PR DESCRIPTION
**Pull request by nSircombe**
# Description

Update Compute Library required version to 22.08

# Checklist

## General

- [X] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [N/A] Have you formatted the code using clang-format?

## Performance improvements

- [N/A] Have you submitted performance data that demonstrates performance improvements?

### New features

- [N/A] Have you published an RFC for the new feature?
- [N/A] Was the RFC approved?
- [N/A] Have you added relevant tests?

### Bug fixes

- [N/A] Have you included information on how to reproduce the issue (either in a github issue or in this PR)?
- [N/A] Have you added relevant regression tests?

### CODE REVIEW

**Comment by nSircombe** [comment]
Note: builds from the upstream master are currently failing - these changes are passing downstream (inc. benchdnn tests) for the v2.7 source.

Note: moving from ACL 22.05 to 22.08 is a prerequisite for changes to the memory formats used for ACL's weights tensors to support variable weights which we will look to raise PRs for in the near future.

**Comment by mgouicem** [comment]
Thanks @nSircombe , do you want us to cherry-pick this change in v2.7?

**Comment by nSircombe** [comment]
Yes please.
...actually I hadn't realised the rls-2.7 branch existed yet - I was expecting the branch in ~1 week?

**Comment by vpirogov** [comment]
@nSircombe, rls-v2.7 was created to support [oneDNN v2.7](https://github.com/oneapi-src/oneDNN/releases/tag/v2.7) release. Changes backported to this branch will be released in v2.7.x patch releases.

**Comment by nSircombe** [comment]
Hi @vpirogov 

Sorry, got my versions muddled - ignore my previous comment, we don't need a this on 2.7.x.

**Review by dzarukin — APPROVED** [review]

**Comment by dzarukin** [comment]
Thank you for the contribution!

**Pull request merged**
