### PR TITLE
Fixes #1120

### LINKED ISSUE #1120: Use CMAKE_CXX_STANDARD to set C++ standards for compilation
# Summary
Use `CMAKE_CXX_STANDARD`, `CMAKE_CXX_STANDARD_REQUIRED `and `CMAKE_CXX_EXTENSIONS `to set C++ standards for compilation as documented in the CMake documentation.

# Version
* git hash 84954971808b7ae0656834cf8e68cabbf086ec28

# Environment
* OS version Windows 10 targeting QNX v7.1
* Compiler version QCC v8.3
* CMake version 3.20.2
* git hash 84954971808b7ae0656834cf8e68cabbf086ec28

# Steps to reproduce
Build for an UNIX target and check the compiler flags.

# Observed behavior
Compiler flags have been manually added at `CMAKE_CXX_FLAGS`.

# Expected behavior
Use `CMAKE_CXX_STANDARD`, `CMAKE_CXX_STANDARD_REQUIRED `and `CMAKE_CXX_EXTENSIONS `to set C++ standards for compilation as documented in the CMake documentation.

### PR DESCRIPTION
**Pull request by pablorcum**
# Description
Use `CMAKE_CXX_STANDARD`, `CMAKE_CXX_STANDARD_REQUIRED `and `CMAKE_CXX_EXTENSIONS `to set C++ standards for compilation.

Fixes #1120

# Checklist

## General

- [x] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [x] Have you formatted the code using clang-format?

### Bug fixes

- [x] Have you included information on how to reproduce the issue (either in a github issue or in this PR)?
- [x] Have you added relevant regression tests?

### CODE REVIEW

**Comment by igorsafo** [comment]
Hi @pablorcum ,
Thanks for your changes. Unfortunately `CMAKE_CXX_STANDARD`, `CMAKE_CXX_STANDARD_REQUIRED` and `CMAKE_CXX_EXTENSIONS` appeared in [CMake 3.1](https://cmake.org/cmake/help/latest/variable/CMAKE_CXX_EXTENSIONS.html) while oneDNN minimal requirement for CMake is 2.8.12, so we couldn't promote the changes as is because it will break oneDNN build with CMake 2.8.12.

Could you please elaborate on the issue you are trying to solve?

**Comment by pablorcum** [comment]
Good point. I haven't noticed the CMake minimum version, thank you very much.

I found out GNU extensions are required in some cases, for example, for crosscompilation for QNX. I took the chance to use the CMake properties listed above but `-std=gnu++11` will also work for now.

**Comment by igorsafo** [comment]
@pablorcum Not sure I understand the initial problem. Is there a part of oneDNN which requires GNU specific C++ extensions? If so we could fix that part of code. Could you please share the logs with build fails?

**Comment by pablorcum** [comment]
I get the following error when crosscompiling for QNX, unless I manually set the define for POSIX_SOURCES. According to the [QNX documentation](http://www.qnx.com/developers/docs/7.1/#com.qnx.doc.neutrino.utilities/topic/q/qcc.html), this is done automatically, if `-std=gnu++11` is used. I don't thing this impact the existing builds and may enable building on other OS.

For now, we could use `-std=gnu++11` and `gnu99` instead of the CMake properties to maintain the compatibility with old CMake versions you mentioned.

```
[  0%] Building CXX object src/cpu/CMakeFiles/dnnl_cpu.dir/bfloat16.cpp.o
In file included from C:/Users/promero/git_work/Utilities/onednn-slrt/oneDNN/src/cpu/x64/cpu_isa_traits.hpp:43,
                 from C:/Users/promero/git_work/Utilities/onednn-slrt/oneDNN/src/cpu/bfloat16.cpp:27:
C:/Users/promero/git_work/Utilities/onednn-slrt/oneDNN/src/cpu/x64/xbyak/xbyak.h:466:4: error: #error "not supported"
   #error "not supported"
    ^~~~~
In file included from c:\programdata\matlab\supportpackages\r2021a\toolbox\slrealtime\target\supportpackage\qnx710\target\qnx7\usr\include\unistd.h:79,
                 from C:/Users/promero/git_work/Utilities/onednn-slrt/oneDNN/src/cpu/x64/xbyak/xbyak.h:127,
                 from C:/Users/promero/git_work/Utilities/onednn-slrt/oneDNN/src/cpu/x64/cpu_isa_traits.hpp:43,
                 from C:/Users/promero/git_work/Utilities/onednn-slrt/oneDNN/src/cpu/bfloat16.cpp:27:
c:\programdata\matlab\supportpackages\r2021a\toolbox\slrealtime\target\supportpackage\qnx710\target\qnx7\usr\include\sys\process.h: In function 'pid_t vfork()':
c:\programdata\matlab\supportpackages\r2021a\toolbox\slrealtime\target\supportpackage\qnx710\target\qnx7\usr\include\sys\process.h:69:12: error: 'fork' was not declared in this scope
     return fork();
            ^~~~
c:\programdata\matlab\supportpackages\r2021a\toolbox\slrealtime\target\supportpackage\qnx710\target\qnx7\usr\include\sys\process.h:69:12: note: suggested alternative: 'vfork'        
     return fork();
            ^~~~
            vfork
In file included from C:/Users/promero/git_work/Utilities/onednn-slrt/oneDNN/src/cpu/x64/cpu_isa_traits.hpp:43,
                 from C:/Users/promero/git_work/Utilities/onednn-slrt/oneDNN/src/cpu/bfloat16.cpp:27:
C:/Users/promero/git_work/Utilities/onednn-slrt/oneDNN/src/cpu/x64/xbyak/xbyak.h: In member function 'virtual uint8_t* Xbyak::MmapAllocator::alloc(size_t)':
C:/Users/promero/git_work/Utilities/onednn-slrt/oneDNN/src/cpu/x64/xbyak/xbyak.h:472:54: error: 'mode' was not declared in this scope
   void *p = mmap(NULL, size, PROT_READ | PROT_WRITE, mode, -1, 0);
                                                      ^~~~
C:/Users/promero/git_work/Utilities/onednn-slrt/oneDNN/src/cpu/x64/xbyak/xbyak.h:472:54: note: suggested alternative: 'modf'
   void *p = mmap(NULL, size, PROT_READ | PROT_WRITE, mode, -1, 0);
                                                      ^~~~
                                                      modf
In file included from C:/Users/promero/git_work/Utilities/onednn-slrt/oneDNN/src/cpu/x64/cpu_isa_traits.hpp:43,
                 from C:/Users/promero/git_work/Utilities/onednn-slrt/oneDNN/src/cpu/bfloat16.cpp:27:
C:/Users/promero/git_work/Utilities/onednn-slrt/oneDNN/src/cpu/x64/xbyak/xbyak.h: In static member function 'static bool Xbyak::CodeArray::protect(const void*, size_t, int)':        
C:/Users/promero/git_work/Utilities/onednn-slrt/oneDNN/src/cpu/x64/xbyak/xbyak.h:1207:29: error: '_SC_PAGESIZE' was not declared in this scope
   size_t pageSize = sysconf(_SC_PAGESIZE);
                             ^~~~~~~~~~~~
C:/Users/promero/git_work/Utilities/onednn-slrt/oneDNN/src/cpu/x64/xbyak/xbyak.h:1207:21: error: 'sysconf' was not declared in this scope
   size_t pageSize = sysconf(_SC_PAGESIZE);
                     ^~~~~~~
C:/Users/promero/git_work/Utilities/onednn-slrt/oneDNN/src/cpu/x64/xbyak/xbyak.h:1207:21: note: suggested alternative: '_sysconf'
   size_t pageSize = sysconf(_SC_PAGESIZE);
                     ^~~~~~~
                     _sysconf
cc: C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/slrealtime/target/supportpackage/qnx710//host/win64/x86_64/usr/lib/gcc/x86_64-pc-nto-qnx7.1.0/8.3.0/cc1plus caught signal 1
src/cpu/CMakeFiles/dnnl_cpu.dir/build.make:75: recipe for target 'src/cpu/CMakeFiles/dnnl_cpu.dir/bfloat16.cpp.o' failed
make.exe[2]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/bfloat16.cpp.o] Error 1
CMakeFiles/Makefile2:323: recipe for target 'src/cpu/CMakeFiles/dnnl_cpu.dir/all' failed
make.exe[1]: *** [src/cpu/CMakeFiles/dnnl_cpu.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make.exe: *** [all] Error 2
```

**Comment by igorsafo** [comment]
I see, thanks for the explanation. I am not sure about the proposed solution, because flags like `gnu++11` are compiler-specific. oneDNN build system has an option to pass additional user-defined compiler options. So when building for QNX you could pass an additional option `-DPOSIX_SOURCES`:
```
(mkdir -p build && cd build && cmake -DCMAKE_SRC_CCXX_FLAGS="-DPOSIX_SOURCES" .. && make -j)
```
As a result compiler line for source files will contain `-DPOSIX_SOURCES`:
```
C_FLAGS =  -fopenmp  -Wall -Wno-unknown-pragmas -fvisibility=internal -msse4.1  -fPIC -Wformat -Wformat-security -fstack-protector-strong -std=c99 -DPOSIX_SOURCES -Wmissing-field-initializers -Wmissing-field-initializers  -Wno-strict-overflow  -O3 -DNDEBUG -D_FORTIFY_SOURCE=2 -fPIC
```
Will this resolve your issue?

**Comment by pablorcum** [comment]
I think we would need `_GNU_SOURCE` then according to [this reference](https://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html).

**Comment by igorsafo** [comment]
> I think we would need `_GNU_SOURCE` then according to [this reference](https://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html).

Were you able to validate it on your side? In this case there are no changes required to oneDNN itself and the option can be added on your side when building oneDNN for QNX.

**Comment by pablorcum** [comment]
Yes, it works on my end. I have added it to my toolchain file. I think, we can then close this pull request and revisit when you have increased the minimum required CMake version.

**Comment by igorsafo** [comment]
The issue is addressed with no required changes to oneDNN.

**Pull request closed without merging**
