### PR TITLE
src: cpu: aarch64: Enable JIT'ed SVE 128 and 256 support for Eltwise …

### PR DESCRIPTION
**Pull request by cfRod**
…primitives

# Description

This PR covers minor changes to enable support for Eltwise primitives for SVE 128 and SVE 256 using the JIT'ed implementation originally added to support SVE 512 (https://github.com/oneapi-src/oneDNN/pull/1092).

# Checklist

## General

- [x] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [x] Have you formatted the code using clang-format?

## Performance improvements

- [ N/A] Have you submitted performance data that demonstrates performance improvements?

### New features

- [X] Have you published an RFC for the new feature?
- [X] Was the RFC approved?
- [N/A] Have you added relevant tests?

### Bug fixes

- [N/A] Have you included information on how to reproduce the issue (either in a github issue or in this PR)?
- [N/A] Have you added relevant regression tests?

## [RFC](https://github.com/oneapi-src/oneDNN/tree/rfcs) PR

- [N/A] Does RFC document follow the [template](https://github.com/oneapi-src/oneDNN/blob/rfcs/rfcs/template.md#onednn-design-document-rfc)?
- [N/A] Have you added a link to the rendered document?

### CODE REVIEW

**Comment by cfRod** [comment]
@kawakami-k,  we noticed  the entry for `CPU_INSTANCE_AARCH64(jit_uni_eltwise_bwd_t<sve_512, f32>)` for the eltwise backward pass inside the "forward" block of the eltwise implementation list ([cpu_eltwise_cpp](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/cpu_eltwise_list.cpp#L64). I have moved this to the backward block.

**Comment by kawakami-k** [comment]
@cfRod 
Thanks for the patch. I will check it in my environment.

**Review by kawakami-k — APPROVED** [review]

**Review by mgouicem — APPROVED** [review]

**Comment by igorsafo** [comment]
@cfRod  The changes landed into master and rls-v2.7. Thanks for your contribution!

**Comment by cfRod** [comment]
Thanks @igorsafo

**Pull request merged**
