### PR TITLE
Implementation for cpu code organization RFC

### PR DESCRIPTION
**Pull request by emfomenk**
# Implementation for cpu code organization RFC #682

Quick glance: [CPU source directory](https://github.com/emfomenk/mkl-dnn/tree/emfomenk/cpu-dir-restructure/src/cpu).

The essence of the changes or how to review the patch:
1. All commits which message **starts** with `style: ` are purely style-related and should not change anything wrt logic. Some of the cosmetic changes happen:
    1. Rename: `jit_uni_layer_normalization` to `simple_layer_normalization`
    2. All files in `src/cpu` include headers using the full path (starts at `src/` directory)
        - This is aligned with `src/gpu`. Later I will update `src/common` too.
    3. Header file guards are normalized: the guard consists of the full file name including the path starting from `src/` directory. E.g. `src/cpu/rnn/rnn_utils.hpp` has `CPU_RNN_RNN_UTILS_HPP` guard.
2. The commits which message **contains** word `style: ` (typically as the second scope) are also style related by are more intrusive or change the behavior.
    1. Rename: `TARGET_ARCH` -> `DNNL_TARGET_ARCH` variable in cmake (attention, @nSircombe)
3. Introduce new file [`cpu/platform.hpp`](https://github.com/emfomenk/mkl-dnn/blob/emfomenk/cpu-dir-restructure/src/cpu/platform.hpp) that contains some generic platform queries + provides macros to work with architecture-specific code + provide an x64-agnostic queries.
    - This file **MUST** be included to make `DNNL_$ARCH` defined.
    - Arch-agnostic code uses `platform::get_cache_line_size()` instead of magic number 64. Same applies to L1 cache size.
    - To check if primitive should support `bf16` or not before we had `IMPLICATION(dt == bf16, mayiuse(avx512_core)`. The proper way to do that now is `platform::has_data_type_support(dt)`.
4. Some kernel implementations, that were containing both reference and jit implementations, were split to facilitate code reorganization:
    - Post-process kernels for inner products;
    - Post-process kernels for int8 convolution;
    - Layer normalization u-kernels;
5. Introduce `src/cpu/x64` sub-directory:
    - Commits:
        - `cpu: introduce x64 subdirectory` and
        - `build: cpu: add custom CMakeLists.txt for cpu/x64`
    - Uses its own `CMakeLists.txt`;
    - `DNNL_ENABLE_JIT_PROFILING` related manipulations happen there now, so non-x64 arches shouldn't worry about this variable being set or unset.
6. GEMM implementation is split into x64-specific and generic parts
7. Finally, make `src/cpu/x64` directory optional:
    - Commits:
        - `build: cpu: make x64 subdirectory optional` ❗ ❗ ❗ 
        - `cpu: x64: introduce dedicated x64 namespace`
        - `cpu: make rnn generic again`
    - Code in `src/cpu/x64` has its own namespace: `dnnl::impl::cpu::x64`. Per convention, the namespace `x64` should go right after `cpu`, nothing should appear in-between.    - Verbose will report `dnnl_verbose,info,cpu,isa:Generic` for non-x64 build now
    - Tests are split into generic and x64-specific ones. Luckily we end up having only 2 x64-specific tests, all other work fine for generic code.
    - Current Int8 RNN examples and older Intel MKL-DNN one were changed to allow int8 RNN return unimplemented (which is currently not supported on non-x64 platforms). Other flavors work fine.
8. Introduced [`cpu/README.md`](https://github.com/emfomenk/mkl-dnn/tree/emfomenk/cpu-dir-restructure/src/cpu#onednn-cpu-implementation), that contains some information on the code organization structure.

Original TODO:
- [x] Add `x64` namespace for `cpu/x64` implementations
- [x] Re-normalize header guards
- [x] Make RNN generic (if time allows)
- [x] Get rid of Cmake warning [1]
- [x] Improve [`cpu/README.md`](https://github.com/emfomenk/mkl-dnn/tree/emfomenk/cpu-dir-restructure/src/cpu#onednn-cpu-implementation)

### x64
``` bash
cmake -DDNNL_TARGET_ARCH="ARCH_GENERIC" .. && make && ctest
```

### ARM AArch64

Should work out of the box. But now the library will be much lighter as it won't contain any x64-spicific code.

## Some differences from the RFC and / or discussion in #682

Macros:
- `DNNL_X64`, `DNNL_AARCH64`, `DNNL_ARCH_GENERIC`: one and only one is defined to `1`, the others are defined to `0`
    - See [here](https://github.com/emfomenk/mkl-dnn/blob/emfomenk/cpu-dir-restructure/src/cpu/platform.hpp#L25-L53).
    - Even though the code in `src/cpu/platform.hpp` may identify the proper platform, the cmake actually passes the platform using `-DDNNL_$ARCH`. This make `src/cpu/platform.hpp` obay the building system. And this is exactly the mechanism that allows building aka non-x64 version on x64 platform (by passing `-DDNNL_TARGET_ARCH="ARCH_GENERIC"` to cmake)
- I borrow @kruus's idea about `IMPLEMENTATION_X64(...)`
- There is no `DNNL_CPU_MAY_SUPPORT_BF16` yet. Probably will live it as is for now. Someone can take over and add it later if there are no strong objections.
- For now ISA lives under `x64` only. Again, if there are no strong objections I suggest keep going with this for now. We probably could revive RFC #664 to make ISA applicable for other arches too. However, I feel I need more deep dive there... 
    - See [here](https://github.com/emfomenk/mkl-dnn/blob/emfomenk/cpu-dir-restructure/src/cpu/x64/cpu_isa_traits.hpp#L46).

### CODE REVIEW

**Comment by kruus** [comment]
Really nice work. I see unexpected benefits everywhere I look!  Rethinking `pp_kernel_t` to move details away from headers into `.cpp` files is elegant. Headers look much cleaner.  I just now realize that we don't need the old, ugly `cpu_barrier.*` for vanilla; vestigial `bfloat16` things in reference primitives have been excised, rather than leaving some reduced functionality etc. etc.

For rnn, the one thorn seems to be `jit_uni_rnn_common_postgemm_dispatcher.hpp`, but it looks to be an easier split than many of the ones you've already cleaned up (nudge, nudge).

**Comment by kruus** [comment]
Comments on "differences" -- basically all is good, except for a remark (below) about cpu dispatch to ref impls.

> * `DNNL_X64`, `DNNL_AARCH64`, `DNNL_ARCH_GENERIC`: one and only one is defined to `1`, the others are defined to `0`
>   * See [here](https://github.com/emfomenk/mkl-dnn/blob/9c96ed95dc316d72c8f7c0340cff31135d20061c/src/cpu/platform.hpp#L33-L58).

This is enough. Forks can still define their own build options at will.

> * There is no `DNNL_CPU_MAY_SUPPORT_BF16` yet. Probably will live it as is for now. Someone can take over and add it later if there are no strong objections.

Excising it from primitives is plenty good enough, eh?  `tests/` can catch up later, to tidy up messages `skipped` primitives.

> * For now ISA lives under `x64` only. Again, if there are no strong objections I suggest keep going with this for now. We probably could revive RFC #664 to make ISA applicable for other arches too. However, I feel I need more deep dive there...
>   

Let's table this.

Suppose I make a `src/mycpu/` subdirectory on my fork.  I'm still perfectly free to create my own version of `cpu_xxx_traits` with whatever semantics I want (features `xxx` conceptually might not even be 'isa'). Of course I can begin with a simplified copy of the `x64/` code, if it's relevant.

>   * See [here](https://github.com/emfomenk/mkl-dnn/blob/emfomenk/cpu-dir-restructure/src/cpu/x64/cpu_isa_traits.hpp#L46).

Visually, I'd guess cpu dispatch is missing a `cpu_isa_traits<isa_any>`, with an added case in `set_max_cpu_isa`?  If you decide to set `user_option_env="ANY"` add a *note* to `dispatcher_control.md`, because ANY and ALL are easily inverted (depending on what you are thinking of at the time).

**Comment by emfomenk** [comment]
Hi @kruus,

Thanks for the quick review and comments! :)

> Excising it from primitives is plenty good enough, eh? tests/ can catch up later, to tidy up messages skipped primitives.

Currently, the tests use `cpu::platform::has_data_type_support(..)` to check if the data type is supported. The addition value of `DNNL_CPU_MAY_SUPPORT_BF16` macro is that it allows to compile code conditionally, hence making the size of the library smaller. But this is definitely not that vital, that's why I slightly de-prioritized it for now.

> Suppose I make a `src/mycpu/` subdirectory on my fork. I'm still perfectly free to create my own version of `cpu_xxx_traits` with whatever semantics I want (features `xxx` conceptually might not even be 'isa'). Of course I can begin with a simplified copy of the `x64/` code, if it's relevant.

Yes, that's how I see it, at least for now. I don't think it makes sense to share the isa stuff between different architectures -- they will most likely be way different. If there is something to share (e.g. we decide to have VANILLA as a first-class citizen isa, #664) we would either have to duplicate the code or move a part of isa-related enums and functions to `cpu/`. In theory, I don't mind either, but this to be thought through :)

> Visually, I'd guess cpu dispatch is missing a `cpu_isa_traits<isa_any>`, with an added case in `set_max_cpu_isa`? If you decide to set `user_option_env="ANY"` add a _note_ to `dispatcher_control.md`, because ANY and ALL are easily inverted (depending on what you are thinking of at the time).

I agree, words `ANY` and `ALL` could be misleading. But, the good thing is that they would never meet each other: `ALL` is (almost) not used inside the library, while `ANY` is not exposed to the interface. The only place where caution is required is exactly `cpu_isa_traits.cpp`.

The implementations should not use `ALL` at all, because they define the constrain on which ISA they work (the lower bound): `ANY` means no special requirements, `SSE41` means sse4.1 is required, ALL doesn't make sense. However, the user is on the other side: they define which ISA the implementations are allowed to use (the upper bound): here `ALL` does make sense. The word `ANY` semantically works too, but for ISA flags it was more convenient to use `any=0` (no special isa-bits required), and `all=~0` (you can use whatever bits, the user doens't care):

``` cpp
enum cpu_isa_t : unsigned {                                    
    isa_any = 0u,                                              
    sse41 = sse41_bit,                                         
    avx = avx_bit | sse41,                                     
    avx2 = avx2_bit | avx,                                     
    avx512_common = avx512_common_bit | avx2,                  
    avx512_mic = avx512_mic_bit | avx512_common,               
    avx512_mic_4ops = avx512_mic_4ops_bit | avx512_mic,        
    avx512_core = avx512_core_bit | avx512_common,             
    avx512_core_vnni = avx512_core_vnni_bit | avx512_core,     
    avx512_core_bf16 = avx512_core_bf16_bit | avx512_core_vnni,
    isa_all = ~0u,                                             
};                                                             
```

So I don't think we ever decide to add `DNNL_MAX_CPU_ISA=ANY`. Even though it sounds better than `ALL` to me :confused:

**Comment by kruus** [comment]
`simple_sum.hpp` and `gemm_convolution_utils.cpp` hardwire a memory cache line size/alignment which might be abstracted into `platform.hpp`. Are the hardwired `src/common` alignments (128 or 64) in `memory_tracking.hpp` and `nstl.hpp` ok for now?

**Comment by emfomenk** [comment]
> `simple_sum.hpp` and `gemm_convolution_utils.cpp` hardwire a memory cache line size/alignment which might be abstracted into `platform.hpp`.

Seems like an easy thing to fix. Will do, thanks.

> Are the hardwired `src/common` alignments (128 or 64) in memory_tracking.hpp and nstl.hpp ok for now?

I'm reluctant to change this for now. Three reasons:
1. This will bring an extra dependency from `common` to `cpu`. Similarly to dependency from `cpu` to `cpu/x64`, I would like to avoid such dependencies. The reason: we should make oneDNN be buildable without CPU backend too (aka GPU-only library). So, I would like to limit any direct references.
2. I could blindly replace `128` with `2 * cache_line_size`, but not sure if this is really brings any value for other architectures. On Intel (CPU? / GPU?) we tested that 128 gives slightly better performance than 64 (I don't know why). I am not sure that `2 * cache_line_size` is actually _the proper_ heuristic for other arches. Hence, as long as 128 works fine for them too, I think the code is good. If it turns out that others may require bigger alignment (e.g. 2048, btw does this mean that the cache line size is 1024?), we can think what to do.
3. (lame excuse) I would like to focus more on the code structure now to promote the huge code refactoring faster and let others rebase on top of these changes. The fine tuning and removing the magic constants could be done slightly later per request and / or PRs.

**Comment by kruus** [comment]
I agree with leaving `src/common/` as is for cache line size.  I didn't see a nicer way to handle it either.

**Comment by nSircombe** [comment]
@emfomenk, this is really great. I've been though and don't see any obvious issues.
I can confirm it builds on Arm 'out of the box' (noting the issue (and my own earlier mistake...) I encountered along the way, which is present in master - #712, which can be addressed after this has merged).

**Comment by nSircombe** [comment]
...oh, one incredibly insignificant nit (as mentioned on https://github.com/emfomenk/mkl-dnn/pull/1) Arm in a sentence shouldn't be caps any more (e.g. ./src/cpu/README.md, line 44).

**Comment by emfomenk** [comment]
> ...oh, one incredibly insignificant nit (as mentioned on emfomenk#1) Arm in a sentence shouldn't be caps any more (e.g. ./src/cpu/README.md, line 44).

I corrected everything in root README.md and doc, but this one was missing.
Thanks for point this out!

**Pull request closed without merging**
