### PR TITLE
Patches needed to compile on FreeBSD.

### PR DESCRIPTION
**Pull request by yurivict**
# Description

ifdefs added for FreeBSD.

### CODE REVIEW

**Review by emfomenk — CHANGES_REQUESTED** [review]
We use scopes in the commit messages for ease of navigation. Could you please change the message to something like: `src: common: enable building on FreeBSD`?

**Comment by yurivict** [comment]
I updated the commit message.

**Review by emfomenk — APPROVED** [review]
Thank you! LGTM!
Will promote the PR soon.

**Comment by emfomenk** [comment]
@yurivict, thank you for the contribution!

**Pull request merged**
