### PR TITLE
src: cpu: aarch64: add checks for supported int8 ACL activations

### PR DESCRIPTION
**Pull request by alenik01**
# Description

Convolutions from Compute Library do not support all the activation functions for `s8`/`u8` datatypes. However, unsupported configurations are not handled properly at the moment in `init_conf_gemm()` checks due to an issue recently discovered in ACL v20.11 (`.validate()` does not return the expected error code). This small fix provides a temporary solution by explicitly checking the unsupported configurations at the stage of primitive descriptor initialisation.

# Checklist

## Code-change submissions

- [X] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally?
- [X] Have you formatted the code using clang-format?

### New features

- [N/A] Have you added relevant tests?
- [N/A] Have you provided motivation for adding a new feature?

### Bug fixes

- [N/A] Have you added relevant regression tests?
- [N/A] Have you included information on how to reproduce the issue (either in a github issue or in this PR)?

### CODE REVIEW

**Review by mgouicem — APPROVED** [review]
LGTM

**Review by dzarukin — APPROVED** [review]
QQ: 1) Does it have to go to master as well (same as https://github.com/oneapi-src/oneDNN/pull/905)?
2) Do I understand right that in case of non-unit alpha, such descriptor will pick reference implementation instead of gemm one and the result should be correct?

**Comment by alenik01** [comment]
@dzarukin,
1). I am not sure about the master. The point here is that once ACL v21.02 will be release in the end of February this fix will no longer be needed.
2). It depends on the activation type. For example, any _alpha_ is supported in the case of bounded_relu. If the conditions are not satisfied, then `_gemm_x8s8s32x_convolution_fwd_t<s8, s8>` or `ref_convolution_fwd_t<s8, s8, s8, s32>` will be picked.

**Comment by alenik01** [comment]
@dzarukin,
>The point here is that once ACL v21.02 will be released in the end of February
oneDNN v2.1 should be released in the middle of January, thus there will be the interval of 1.5 months between releases, and it is indeed better to put these changes into the master.

**Pull request merged**
