### PR TITLE
cpu: aarch64: remove unused variable and fix no return function

### PR DESCRIPTION
**Pull request by kawakami-k**
# Description

This PR fixes build error -Werror and no return of non-void function.

# Checklist

## Code-change submissions

- [X] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally?
- [X] Have you formatted the code using clang-format?

### CODE REVIEW

**Review by igorsafo — APPROVED** [review]
The changes LGTM, thanks!

**Comment by nSircombe** [comment]
HI @kawakami-k 
Thanks for posting this fix - this issue filtered into our downstream builds yesterday, I'd not had chance to raise and issue, but this fixes it for me!

I'm a little confused why the CI didn't catch the problem on the original PR? A cursory glance appears to show it went through ok - https://cloud.drone.io/oneapi-src/oneDNN/379/3/2, but I may be missing something.

Anyway, looks good to me!

**Comment by kawakami-k** [comment]
Hi @nSircombe 

Thank you for the comment.

`-Werror` option may be disabled by `-w`.
`-w` is recently removed for GCC. 
https://github.com/oneapi-src/oneDNN/commit/702c4f703312241b0c3d3330ffd3cb7d38b9b552

**Comment by nSircombe** [comment]
Ah. Thanks @kawakami-k, I hadn't spotted the appearance (and subsequent removal of) that `-w` flag.

**Comment by kawakami-k** [comment]
@igorsafo rls-v2.1 branch also requires this patch to build and pass CI. Should I also submit this PR for rls-v2.1 branch?

**Comment by dzarukin** [comment]
Hi @kawakami-k, I'm going to promote every PR that is promotable for master right away. For v2.1 I'll take #963 and cherry-pick changes from this PR at first. No need in pushing one more PR. Are you fine with it? Thanks.

**Comment by kawakami-k** [comment]
Thanks. It's fine.

**Comment by dzarukin** [comment]
Thanks for your contribution!

**Pull request merged**
