### PR TITLE
jit:blk reorder optimisation extension for FX700

### PR DESCRIPTION
**Pull request by Shreyas-fuj**
# Description

Some of the optimizations for the jit:blk reorder were done for GR3 in this PR - https://github.com/oneapi-src/oneDNN/pull/1986 .
The same is extended to work on FX700 as well.

# Checklist

## General

- [y] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
```
make test

99% tests passed, 2 tests failed out of 197

Total Test time (real) = 652.57 sec

The following tests FAILED:
        156 - test_graph_unit_dnnl_large_partition_usm_cpu (Failed)
        178 - test_benchdnn_modeC_graph_ci_cpu (Failed)
Errors while running CTest
Output from these tests are in: /home/shreyas/G/shr-fuj/oneDNN_open_source/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
make: *** [Makefile:71: test] Error 8
```
- [y] Have you formatted the code using clang-format?

### CODE REVIEW

**Comment by jondea** [comment]
From what I can tell, these changes could impact performance on machines with vector lengths != 512. I assume you have tested a vector length of 512 using an A64FX, but do we need to do regression tests for 256 and 128 too? Also, do you have any data on the speedup you have seen?

**Comment by Shreyas-fuj** [comment]
Hi @jondea,
In PR : https://github.com/oneapi-src/oneDNN/pull/1986, we had 3 optimisations, 2 were development of jit:blk kernels for 32 and 64 block sizes which gave boost over jit:uni kernels, and the 3rd one was optimisation of 8x8 kernel. The last optimisation was done only for GR3 which resulted in testy cases failing on FX700. Therefore, only this optimisation is rolled back to the previous version(as it was before  https://github.com/oneapi-src/oneDNN/pull/1986) until we can optimise it jointly for FX700. The remaining optimisations i.e, development of jit:blk kernels for 32 and 64 block sizes remain intact.

**Comment by theComputeKid** [comment]
Having a look at the logs for jit:blk reorders, seems like we are ok with sve perf on g3 after this change. I'll leave it to @jondea to give final approval, but it's OK from me.

**Review by theComputeKid — APPROVED** [review]

**Review by jondea — APPROVED** [review]
LGTM, thank you for the contribution!

**Pull request merged**
